ci: add AWS CodeBuild buildspec for quic-attack (#2003)
* add buildspec.yml

* add -y command to run rustup accepting defaults

* install cmake

* use stable for installing ultraman

* use debug build while testing

* set SHELL env variable

* trying without eval

* change to debug

* put eval back

* exit with 0 only if the time limit was reached

* add new line to buildspec.yml

* add new line to run

* use environment variable for runtime

* Add message

* change pkill input

* try out a panic

* remove panic

* add quotes to pkill

* try panic again

* remove panic

diff --git a/scripts/quic-attack/run b/scripts/quic-attack/run
--- a/scripts/quic-attack/run
+++ b/scripts/quic-attack/run
@@ -8,11 +8,14 @@
 set -e
 
 # ensure s2n-quic-qns is built
-RUSTFLAGS="-C debug_assertions --cfg s2n_internal_dev -g" cargo +stable build --release --bin s2n-quic-qns
+# -C debug_assertions turns on debug assertions and overflow checks in the release build
+# -g include debug information
+# -C panic=abort will cause spawned tasks that panic to exit the process
+RUSTFLAGS="-C debug_assertions --cfg s2n_internal_dev -g -C panic=abort" cargo +stable build --release --bin s2n-quic-qns
 
 # ensure ultraman is installed
 if ! command -v ultraman &> /dev/null; then
-    cargo install ultraman
+    cargo +stable install ultraman
 fi
 
 # The different types of fuzzing supported by quic-attack
@@ -55,7 +58,17 @@ fi
 COMMON_ARGS="--max-throughput 10000 --max-handshake-duration 10 --max-idle-timeout 10"
 PERF_APP="./target/release/s2n-quic-qns perf"
 
+# disable exiting on errors to capture the timeout status
+set +e
 RUST_BACKTRACE=1 \
 SERVER="$PERF_APP server $COMMON_ARGS" \
 CLIENT="$PERF_APP client $COMMON_ARGS --ip 127.0.0.1 --local-ip 127.0.0.1 --connections 100000000000000000 --send 100000 --receive 100000 --streams 10000 --concurrency 1000" \
 $TIMEOUT ultraman start --no-timestamp true -f ./scripts/quic-attack/Procfile -m $PROCESSES
+EXIT_CODE="$?"
+# cleanup any zombie processes
+pkill -f "$PERF_APP"
+# re-enable exiting on errors
+set -e
+# `timeout` exits with `124` if the time limit was reached
+# only exit with a success code if the time limit was reached
+[[ "$EXIT_CODE" == "124" ]] || exit 1
